#
# Makefile for HDR
#
# Compiler: g++/gcc
# Linker: g++/gcc
#
#
CC:=gcc
CCFLAGS:=-g -O3
RM:=rm -f
HISTSRCDIR:=./HdrHistogram_c/src

hdr_histogram.o: $(HISTSRCDIR)/hdr_histogram.c 
	$(CC) $(CCFLAGS) -c $<
